class GeneralSettingSerializer < ActiveModel::Serializer
  attributes :id, :prefix, :minimum_digits



attribute :use_auto_generated_number_for_service_provider, if: :include_use_auto_generated_number_for_service_provider?


attribute :use_auto_generated_number, if: :include_autogenerated_number? 



def include_use_auto_generated_number_for_service_provider?
  instance_options[:context][:use_auto_generated_number_for_service_provider] == 'true'

end
def include_autogenerated_number?
  instance_options[:context][:use_auto_generated_number] == 'true'
end


def use_auto_generated_number_for_service_provider
  true
end

def use_auto_generated_number
  true
end
end
