class GeneralSettingSerializer < ActiveModel::Serializer
  attributes :id, :prefix, :minimum_digits



attribute :use_auto_generated_number_for_service_provider, if: :include_use_auto_generated_number_for_service_provider?
attribute :send_sms_and_email, if: :include_send_sms_and_email?
attribute :send_sms_and_email_for_provider, if: :include_send_sms_and_email_for_provider?
attribute :use_auto_generated_number, if: :include_autogenerated_number? 
attribute :login_with_otp, if: :include_login_with_otp?




def include_login_with_otp?
  instance_options[:context][:login_with_otp] == 'true'  || instance_options[:context][:login_with_otp] == true
end


def include_send_sms_and_email?
  instance_options[:context][:send_sms_and_email] == 'true'

end


def include_send_sms_and_email_for_provider?
  instance_options[:context][:send_sms_and_email_for_provider] == 'true'

end



def include_use_auto_generated_number_for_service_provider?
  instance_options[:context][:use_auto_generated_number_for_service_provider] == 'true'

end



def include_autogenerated_number?
  instance_options[:context][:use_auto_generated_number] == 'true'
end


def use_auto_generated_number_for_service_provider
  true
end

def use_auto_generated_number
  true
end


def send_sms_and_email
  true
end


def send_sms_and_email_for_provider
  true
end


def login_with_otp
  true
end

end
