class PrefixAndDigitSerializer < ActiveModel::Serializer
  attributes :id, :prefix, :minimum_digits





attribute :use_auto_generated_number, if: :include_autogenerated_number? 
attribute :send_sms_and_email, if: :include_send_sms_and_email?
attribute :enable_2fa, if: :include_enable_2fa?
attribute :send_email, if: :include_send_email?




def include_enable_2fa?
  instance_options[:context][:enable_2fa] == true
end


def include_send_email?
  instance_options[:context][:send_email] == true
end

def include_autogenerated_number?
  instance_options[:context][:use_auto_generated_number] == true 
end

def include_send_sms_and_email?
  instance_options[:context][:send_sms_and_email] == true

end

def send_email
  true
end

def enable_2fa
  true
end


def send_sms_and_email
  true
end


def use_auto_generated_number
  true
end





end
